core/urls.py
from django.urls import path 
from core import views 
from core.views import pages_view,albums_view,chats_friend_view

app_name = "core"

urlpatterns = [
    path("", views.index, name="feed"),
    path("post/<slug:slug>/", views.post_detail, name="post-detail"),

    # Chat Feature
    path("core/inbox/", views.inbox, name="inbox"),
    path("core/inbox/<username>/", views.inbox_detail, name="inbox_detail"),

    # Group CHat
    path("core/group-inbox/", views.group_inbox, name="group_inbox"),
    path("core/group-inbox/<slug:slug>/", views.group_inbox_detail, name="group_inbox_detail"),
    path("core/create-group/", views.create_group_page, name="create_group_page"),
    path('groups.html', views.groups_view, name='groups'),
    path('pages.html', pages_view, name='pages'),
    path('albums.html', albums_view, name='albums'),
    path('timeline-page.html', views.timeline_page, name='timeline_page'),
    path('videos.html', views.videos_page, name='videos_page'),

    # Join & leave Group
    path("core/join-group-page/<slug:slug>/", views.join_group_chat_page, name="join_group_chat_page"),
    path("core/join-group/<slug:slug>/", views.join_group_chat, name="join_group"),
    path("core/leave-group/<slug:slug>/", views.leave_group_chat, name="leave_group_chat"),
    path('chats-friend.html', chats_friend_view, name='chats_friend'), 
    # Games
    path("core/all-games/", views.games, name="games"),
    path("core/stack_brick/", views.stack_brick, name="stack_brick"),

    # Search
    path('search/', views.search_users, name='search_users'),

    # Load more post
    path('load_more_posts/', views.load_more_posts, name='load_more_posts'),




    # Ajax URLs
    path("create-post/", views.create_post, name="create-post"),
    path("like-post/", views.like_post, name="like-post"),
    path("comment-post/", views.comment_on_post, name="comment-post"),
    path("like-comment/", views.like_comment, name="like-comment"),
    path("reply-comment/", views.reply_comment, name="reply-comment"),
    path("delete-comment/", views.delete_comment, name="delete-comment"),
    path("add-friend/", views.add_friend, name="add-friend"),
    path("accept-friend-request/", views.accept_friend_request, name="accept-friend-request"),
    path("reject-friend-request/", views.reject_friend_request, name="reject-friend-request"),
    path("unfriend/", views.unfriend, name="unfriend"),
    path("block-user/", views.block_user, name="block_user"),
]

novelconnection/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from core.routing import websocket_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),

    # Routing
    path("user/", include("userauths.urls")),
    path("", include("core.urls")),

    # Web Socket
    path('ws/', include(websocket_urlpatterns)),

    # Change Password
    path('user/change-password/',auth_views.PasswordChangeView.as_view(template_name='userauths/password-reset/change-password.html',success_url = '/user/password-reset-complete/'),name='change_password'),
    path('user/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='userauths/password-reset/password_reset_complete.html'), name='password_reset_complete'),

    

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


userauths/urls.py
from django.urls import path 
from userauths import views 

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.RegisterView, name="sign-up"),
    path("sign-in/", views.LoginView, name="sign-in"),
    path("sign-out/", views.LogoutView, name="sign-out"),

    path("my-profile/", views.my_profile, name="my-profile"),
    path("profile/<username>/", views.friend_profile, name="profile"),

    path("profile-update/", views.profile_update, name="profile-update"),

]

templates/partials/settings_sidebar.html
<div class="lg:w-1/3">
    <nav class="responsive-nav setting-nav setting-menu"
        uk-sticky="top:30 ; offset:80 ; media:@m ;bottom:true; animation: uk-animation-slide-top">
        <h4 class="mb-0 p-3 uk-visible@m hidden"> Setting Navigation </h4>
        <ul>
            <li class="{% if request.path == '/user/profile-update/' %}uk-active{% endif %}"><a href="{% url 'userauths:profile-update' %}"> <i class="uil-cog"></i> General </a></li>
            <li class="{% if request.path == '/user/change-password/' or request.path == '/user/password-reset-complete/' %}uk-active{% endif %}"><a href="{% url 'change_password' %}"> <i class="uil-unlock-alt"></i> Password </a></li>
            <li><a href="#"> <i class="uil-shield-check"></i> Security</a></li>
            <!-- <li><a href="#"> <i class="uil-bolt"></i> Membership</a></li> -->
            <!-- <li><a href="#"> <i class="uil-history"></i> Manage Sessions</a></li> -->
            <li><a href="#"> <i class="uil-trash-alt"></i> Delete account</a></li>
        </ul>
    </nav>
</div>