core/urls.py
from django.urls import path 
from core import views 
from core.views import pages_view,albums_view,chats_friend_view

app_name = "core"

urlpatterns = [
    path("", views.index, name="feed"),
    path("post/<slug:slug>/", views.post_detail, name="post-detail"),

    # Chat Feature
    path("core/inbox/", views.inbox, name="inbox"),
    path("core/inbox/<username>/", views.inbox_detail, name="inbox_detail"),

    # Group CHat
    path("core/group-inbox/", views.group_inbox, name="group_inbox"),
    path("core/group-inbox/<slug:slug>/", views.group_inbox_detail, name="group_inbox_detail"),
    path("core/create-group/", views.create_group_page, name="create_group_page"),
    path('groups.html', views.groups_view, name='groups'),
    path('pages.html', pages_view, name='pages'),
    path('albums.html', albums_view, name='albums'),
    path('timeline-page.html', views.timeline_page, name='timeline_page'),
    path('videos.html', views.videos_page, name='videos_page'),

    # Join & leave Group
    path("core/join-group-page/<slug:slug>/", views.join_group_chat_page, name="join_group_chat_page"),
    path("core/join-group/<slug:slug>/", views.join_group_chat, name="join_group"),
    path("core/leave-group/<slug:slug>/", views.leave_group_chat, name="leave_group_chat"),
    path('chats-friend.html', chats_friend_view, name='chats_friend'), 
    # Games
    path("core/all-games/", views.games, name="games"),
    path("core/stack_brick/", views.stack_brick, name="stack_brick"),

    # Search
    path('search/', views.search_users, name='search_users'),

    # Load more post
    path('load_more_posts/', views.load_more_posts, name='load_more_posts'),




    # Ajax URLs
    path("create-post/", views.create_post, name="create-post"),
    path("like-post/", views.like_post, name="like-post"),
    path("comment-post/", views.comment_on_post, name="comment-post"),
    path("like-comment/", views.like_comment, name="like-comment"),
    path("reply-comment/", views.reply_comment, name="reply-comment"),
    path("delete-comment/", views.delete_comment, name="delete-comment"),
    path("add-friend/", views.add_friend, name="add-friend"),
    path("accept-friend-request/", views.accept_friend_request, name="accept-friend-request"),
    path("reject-friend-request/", views.reject_friend_request, name="reject-friend-request"),
    path("unfriend/", views.unfriend, name="unfriend"),
    path("block-user/", views.block_user, name="block_user"),
]

novelconnection/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from core.routing import websocket_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),

    # Routing
    path("user/", include("userauths.urls")),
    path("", include("core.urls")),

    # Web Socket
    path('ws/', include(websocket_urlpatterns)),

    # Change Password
    path('user/change-password/',auth_views.PasswordChangeView.as_view(template_name='userauths/password-reset/change-password.html',success_url = '/user/password-reset-complete/'),name='change_password'),
    path('user/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='userauths/password-reset/password_reset_complete.html'), name='password_reset_complete'),

    

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


userauths/urls.py
from django.urls import path 
from userauths import views 

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.RegisterView, name="sign-up"),
    path("sign-in/", views.LoginView, name="sign-in"),
    path("sign-out/", views.LogoutView, name="sign-out"),

    path("my-profile/", views.my_profile, name="my-profile"),
    path("profile/<username>/", views.friend_profile, name="profile"),

    path("profile-update/", views.profile_update, name="profile-update"),

]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser 
from django.db.models.signals import post_save
from django.utils.html import mark_safe


from PIL import Image
from shortuuid.django_fields import ShortUUIDField



RELATIONSHIP = (
    ("single","Single"),
    ("married","married"),
    ("inlove","In Love"),
)


GENDER = (
    ("female", "Female"),
    ("male", "Male"),
)

WHO_CAN_SEE_MY_FRIENDS = (
    ("Only Me","Only Me"),
    ("Everyone","Everyone"),
)


def user_directory_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (instance.user.id, ext)
    return 'user_{0}/{1}'.format(instance.user.id,  filename)

class User(AbstractUser):
    full_name = models.CharField(max_length=1000, null=True, blank=True)
    username = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=100, null=True, blank=True)
    gender = models.CharField(max_length=100, choices=GENDER, null=True, blank=True)

    otp = models.CharField(max_length=100, null=True, blank=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return str(self.username)



class Profile(models.Model):
    pid = ShortUUIDField(length=7, max_length=25, alphabet="abcdefghijklmnopqrstuvxyz123")
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cover_image = models.ImageField(upload_to=user_directory_path, default="cover.jpg", blank=True, null=True)
    image = models.ImageField(upload_to=user_directory_path, default="default.jpg", null=True, blank=True)
    full_name = models.CharField(max_length=1000, null=True, blank=True)
    bio = models.CharField(max_length=100, null=True, blank=True)
    about_me = models.CharField( max_length=1000,null=True, blank=True)
    phone = models.CharField(max_length=100, null=True, blank=True)
    gender = models.CharField(max_length=100, choices=GENDER, null=True, blank=True)
    relationship = models.CharField(max_length=100, choices=RELATIONSHIP, null=True, blank=True, default="single")
    friends_visibility = models.CharField(max_length=100, choices=WHO_CAN_SEE_MY_FRIENDS, null=True, blank=True, default="Everyone")
    country = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    state = models.CharField(max_length=100, null=True, blank=True)
    address = models.CharField(max_length=1000, null=True, blank=True)
    working_at = models.CharField(max_length=1000, null=True, blank=True)
    instagram = models.URLField(default="https://instagram.com/", null=True, blank=True)
    whatsApp = models.CharField(default="+123 (456) 789", max_length=100, blank=True, null=True)
    verified = models.BooleanField(default=False)
    followers = models.ManyToManyField(User, blank=True, related_name="followers")
    followings = models.ManyToManyField(User, blank=True, related_name="followings")
    friends = models.ManyToManyField(User, blank=True, related_name="friends")
    groups = models.ManyToManyField("core.Group", blank=True, related_name="groups")
    pages = models.ManyToManyField("core.Page", blank=True, related_name="pages")
    blocked = models.ManyToManyField(User, blank=True, related_name="blocked")
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        if self.full_name:
            return str(self.full_name)
        else:
            return str(self.user.username)


    # def save(self, *args, **kwargs):
    #     img = Image.open(self.image.path)
    #     if img.height > 700 or img.width > 700:
    #         output_size = (700, 700)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)
    #     super().save(*args, **kwargs)

    
    def thumbnail(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" object-fit:"cover" style="border-radius: 30px;" />' % (self.image))

    
    
def create_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)

def save_user_profile(sender, instance, **kwargs):
	instance.profile.save()


post_save.connect(create_user_profile, sender=User)
post_save.connect(save_user_profile, sender=User)


userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ImageField, FileInput, TextInput, Select

from userauths.models import Profile, User

class UserRegisterForm(UserCreationForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={'class': '', 'id': "", 'placeholder':'Full Name'}), max_length=100, required=True)
    username = forms.CharField(widget=forms.TextInput(attrs={'class': '', 'id': "", 'placeholder':'Username'}), max_length=100, required=True)
    phone = forms.CharField(widget=forms.TextInput(attrs={'class': '', 'id': "", 'placeholder':'Mobile No.'}), max_length=100, required=True)
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': '' , 'id': "", 'placeholder':'Email Address'}), required=True)
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'id': "", 'placeholder':'Password'}), required=True)
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'id': "", 'placeholder':'Confirm Password'}), required=True)
    # gender = forms.CharField(widget=forms.TextInput(attrs={ 'class': 'with-border' , 'id': "", 'placeholder':'Enter Gender'}))
    
    class Meta:
        model = User
        fields = ['full_name', 'username', 'email', 'password1', 'password2', 'phone', 'gender']


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'with-border'
            # visible.field.widget.attrs['placeholder'] = visible.field.label


class ProfileUpdateForm(forms.ModelForm):
    image = ImageField(widget=FileInput)
    
    class Meta:
        model = Profile
        fields = [
            'cover_image' ,
            'image' ,
            'full_name', 
            'bio', 
            'about_me', 
            'phone',
            'gender',
            'relationship',
            'friends_visibility',
            'country', 
            'city', 
            'state', 
            'address', 
            'working_at',
            'instagram',
            'whatsApp',
        ]

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']

userauths/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required

from userauths.models import User, Profile
from userauths.forms import UserRegisterForm, ProfileUpdateForm, UserUpdateForm
from core.models import FriendRequest, Post


def RegisterView(request, *args, **kwargs):
    if request.user.is_authenticated:
        messages.warning(request, f"Hey {request.user.username}, you are already logged in")
        return redirect('core:feed')   

    form = UserRegisterForm(request.POST or None)
    if form.is_valid():
        form.save()
        full_name = form.cleaned_data.get('full_name')
        phone = form.cleaned_data.get('phone')
        email = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password1')

        user = authenticate(email=email, password=password)
        login(request, user)

        messages.success(request, f"Hi {request.user.username}, your account have been created successfully.")

        profile = Profile.objects.get(user=request.user)
        profile.full_name = full_name
        profile.phone = phone
        profile.save()

        return redirect('core:feed')
    
    context = {'form':form}
    return render(request, 'userauths/sign-up.html', context)

def LoginView(request):
    # if request.user.is_authenticated:
    #     return redirect('core:feed')
    
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        try:
            user = User.objects.get(email=email)

            user = authenticate(request, email=email, password=password)

            if user is not None:
                login(request, user)
                messages.success(request, "You are Logged In")
                return redirect('core:feed')
            else:
                messages.error(request, 'Username or password does not exit.')
        
        except:
            messages.error(request, 'User does not exist')

    return HttpResponseRedirect("/")

def LogoutView(request):
    logout(request)
    messages.success(request, 'You have been logged out')
    return redirect("userauths:sign-in")


@login_required
def my_profile(request):
    profile = request.user.profile
    posts = Post.objects.filter(active=True, user=request.user)

    context = {
        "posts":posts,
        "profile":profile,
    }
    return render(request, "userauths/my-profile.html", context)


@login_required
def friend_profile(request, username):
    profile = Profile.objects.get(user__username=username)
    posts = Post.objects.filter(active=True, user=profile.user)

    # Send Friend Request Feature
    bool = False
    bool_friend = False

    sender = request.user
    receiver = profile.user
    bool_friend = False
    print("========================  Add or cancel")
    try:
        friend_request = FriendRequest.objects.get(sender=sender, receiver=receiver)
        if friend_request:
            bool = True
        else:
            bool = False
    except:
        bool = False
    # if receiver not in sender.profile.friends.all():
    #     pass
    # else:
    #     print("========================  Unfriend")
    #     bool_friend = False

    # End Send Friend Request Feature
    print("Bool =======================", bool)
    

    context = {
        "posts":posts,
        "bool_friend":bool_friend,
        "bool":bool,
        "profile":profile,
    }
    return render(request, "userauths/friend-profile.html", context)


@login_required
def profile_update(request):
    if request.method == "POST":
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        u_form = UserUpdateForm(request.POST, instance=request.user)

        if p_form.is_valid() and u_form.is_valid():
            p_form.save()
            u_form.save()
            messages.success(request, "Profile Updated Successfully.")
            return redirect('userauths:profile-update')
    else:
        p_form = ProfileUpdateForm(instance=request.user.profile)
        u_form = UserUpdateForm(instance=request.user)

    context = {
        'p_form': p_form,
        'u_form': u_form,
    }
    return render(request, 'userauths/profile-update.html', context)


templates/userauths/profile-update.html
{% extends 'partials/base.html' %}
{% load static %}
{% load widget_tweaks  %}
{% block content %}

        <style>
            
            #id_image{
                background-color: #270041;
                border-radius: 4px;
                height: 50px;
                width: 100%;
                color: #ffffff;
            }
            #id_image::file-selector-button{
                border: none;
                border-radius: 7px;
                color: 432f9f;
                background-color: #ffffff;
                height: 30px;
                cursor: pointer;
                transition: all .25s ease-in;
                margin-top: 1px;
                margin-left: 10px;
            }
        </style>


        <!-- Main Contents -->
        <div class="main_content">
            <div class="mcontainer">

                <div class="bg-white lg:divide-x lg:flex lg:shadow-md rounded-md shadow lg:rounded-xl overflow-hidden lg:m-0 -mx-4">
                    
                    {% include 'partials/settings_sidebar.html' %}
                    <div class="lg:w-2/3">

                        

                        <form method="POST" class="lg:flex lg:flex-col justify-between lg:h-full" enctype="multipart/form-data">
                            {% csrf_token %}
                            <!-- form header -->
                            <div class="lg:px-10 lg:py-8 p-6">
                                <h3 class="font-bold mb-2 text-xl">Profile</h3>
                                <p class=""> This information will be dispalyed publicly so be carful what you share. </p>
                            </div>

                            <!-- form body -->
                            <div class="lg:py-8 lg:px-20 flex-1 space-y-4 p-6">

                                

                                <h4><b>Personal</b></h4>
                                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                                    <!-- Column 1: Profile Image -->
                                    <div class="bg-gray-100 p-4  flex items-center" style="border-radius: 10px;">
                                        <div class="relative">
                                            <img src="{{request.user.profile.image.url}}" id="preview_avatar" alt="Profile Picture" class="w-24 h-24 rounded-full">
                                            <label for="id_image" class="absolute bottom-0 right-0 p-2 bg-white rounded-full cursor-pointer">
                                                <i class="fas fa-pen text-blue-500"></i>
                                            </label>
                                        </div>
                                    </div>


                                    <!-- Column 2: Cover Image -->
                                    <div class="bg-blue-100 p-4" style="border-radius: 10px;">
                                        <div class="relative">
                                        <img src="{{request.user.profile.cover_image.url}}" id="preview_cover" alt="Cover Image" class="w-full h-32 object-cover rounded-lg">
                                        <label for="id_cover_image" class="absolute bottom-0 right-0 p-2 bg-white rounded-full cursor-pointer">
                                            <i class="fas fa-pen text-blue-500"></i>
                                        </label>
                                        </div>
                                    </div>

                                    <script>
                                        var loadFile = function (event) {
                                          var output2 = document.getElementById("preview_avatar");
                                          output2.src = URL.createObjectURL(event.target.files[0]);
                                          output2.onload = function () {
                                            URL.revokeObjectURL(output2.src); // free memory
                                          };
                                        };

                                        var loadFile2 = function (event) {
                                          var output2 = document.getElementById("preview_cover");
                                          output2.src = URL.createObjectURL(event.target.files[0]);
                                          output2.onload = function () {
                                            URL.revokeObjectURL(output2.src); // free memory
                                          };
                                        };
                                      </script>

                                </div>
                                <div class="d-none">
                                    <div class="line">
                                        {% render_field p_form.image onchange="loadFile(event)" class="hidden"  %}
                                    </div>
                                    <div class="line">
                                        {% render_field p_form.cover_image onchange="loadFile2(event)" class="hidden"  %}
                                    </div>
                                </div>
                                <div class="line">
                                    {% render_field p_form.full_name class="line__input" %}
                                    <span for="username" class="line__placeholder"> First Name   </span>
                                </div>
                                <div class="line">
                                    {% render_field p_form.bio class="line__input"  %}
                                    <span for="username" class="line__placeholder"> Bio  </span>
                                </div>
                                <div class="line">
                                    {% render_field p_form.about_me class="line__input" %}
                                    <span for="username" class="line__placeholder"> About Me   </span>
                                </div>
                                <div class="line">
                                    {% render_field p_form.relationship class="line__input" %}
                                    <span for="username" class="line__placeholder"> Relationship Status   </span>
                                </div>
                            </div>

                            <div class="lg:py-4 lg:px-20 flex-1 space-y-4 p-6">
                                <h4><b>Contact</b></h4>
                                <div class="line">
                                    {% render_field p_form.phone class="line__input" %}
                                    <span for="username" class="line__placeholder"> Mobile Number   </span>
                                </div>
                                <div class="line">
                                    {% render_field u_form.email class="line__input" %}
                                    <span for="username" class="line__placeholder"> Email  </span>
                                </div>
                            </div>

                            <div class="lg:py-4 lg:px-20 flex-1 space-y-4 p-6">
                                <h4><b>Address</b></h4>
                                <div class="line">
                                    {% render_field p_form.address class="line__input" %}
                                    <span for="username" class="line__placeholder"> Address   </span>
                                </div>
                                <div class="line">
                                    {% render_field p_form.city class="line__input" %}
                                    <span for="username" class="line__placeholder"> City  </span>
                                </div>
                                <div class="line">
                                    {% render_field p_form.state class="line__input" %}
                                    <span for="username" class="line__placeholder"> State  </span>
                                </div>
                                <div class="line">
                                    {% render_field p_form.country class="line__input" %}
                                    <span for="username" class="line__placeholder"> State  </span>
                                </div>
                            </div>

                            <div class="lg:py-4 lg:px-20 flex-1 space-y-4 p-6">
                                <h4><b>Address</b></h4>
                                <div class="line">
                                    {% render_field p_form.address class="line__input" %}
                                    <span for="username" class="line__placeholder"> Address   </span>
                                </div>
                                <div class="line">
                                    {% render_field p_form.city class="line__input" %}
                                    <span for="username" class="line__placeholder"> City  </span>
                                </div>
                                <div class="line">
                                    {% render_field p_form.state class="line__input" %}
                                    <span for="username" class="line__placeholder"> State  </span>
                                </div>
                                <div class="line">
                                    {% render_field p_form.country class="line__input" %}
                                    <span for="username" class="line__placeholder"> State  </span>
                                </div>
                            </div>

                            <div class="lg:py-4 lg:px-20 flex-1 space-y-4 p-6">
                                <h4><b>Socila URLs</b></h4>
                                <div class="line">
                                    {% render_field p_form.instagram class="line__input" %}
                                    <span for="username" class="line__placeholder"> Instagram   </span>
                                </div>
                                <div class="line">
                                    {% render_field p_form.whatsApp class="line__input" %}
                                    <span for="username" class="line__placeholder"> WhatsApp  </span>
                                </div>
                            </div>

                            <div class="bg-gray-10 p-6 pt-0 flex justify-end space-x-3">
                                <button type="submit" class="button bg-blue-700"> Save Changes </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

{% endblock content %}