core/urls.py
from django.urls import path 
from core import views 
from core.views import pages_view,albums_view,chats_friend_view

app_name = "core"

urlpatterns = [
    path("", views.index, name="feed"),
    path("post/<slug:slug>/", views.post_detail, name="post-detail"),

    # Chat Feature
    path("core/inbox/", views.inbox, name="inbox"),
    path("core/inbox/<username>/", views.inbox_detail, name="inbox_detail"),

    # Group CHat
    path("core/group-inbox/", views.group_inbox, name="group_inbox"),
    path("core/group-inbox/<slug:slug>/", views.group_inbox_detail, name="group_inbox_detail"),
    path("core/create-group/", views.create_group_page, name="create_group_page"),
    path('groups.html', views.groups_view, name='groups'),
    path('pages.html', pages_view, name='pages'),
    path('albums.html', albums_view, name='albums'),
    path('timeline-page.html', views.timeline_page, name='timeline_page'),
    path('videos.html', views.videos_page, name='videos_page'),

    # Join & leave Group
    path("core/join-group-page/<slug:slug>/", views.join_group_chat_page, name="join_group_chat_page"),
    path("core/join-group/<slug:slug>/", views.join_group_chat, name="join_group"),
    path("core/leave-group/<slug:slug>/", views.leave_group_chat, name="leave_group_chat"),
    path('chats-friend.html', chats_friend_view, name='chats_friend'), 
    # Games
    path("core/all-games/", views.games, name="games"),
    path("core/stack_brick/", views.stack_brick, name="stack_brick"),

    # Search
    path('search/', views.search_users, name='search_users'),

    # Load more post
    path('load_more_posts/', views.load_more_posts, name='load_more_posts'),




    # Ajax URLs
    path("create-post/", views.create_post, name="create-post"),
    path("like-post/", views.like_post, name="like-post"),
    path("comment-post/", views.comment_on_post, name="comment-post"),
    path("like-comment/", views.like_comment, name="like-comment"),
    path("reply-comment/", views.reply_comment, name="reply-comment"),
    path("delete-comment/", views.delete_comment, name="delete-comment"),
    path("add-friend/", views.add_friend, name="add-friend"),
    path("accept-friend-request/", views.accept_friend_request, name="accept-friend-request"),
    path("reject-friend-request/", views.reject_friend_request, name="reject-friend-request"),
    path("unfriend/", views.unfriend, name="unfriend"),
    path("block-user/", views.block_user, name="block_user"),
]

novelconnection/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from core.routing import websocket_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),

    # Routing
    path("user/", include("userauths.urls")),
    path("", include("core.urls")),

    # Web Socket
    path('ws/', include(websocket_urlpatterns)),

    # Change Password
    path('user/change-password/',auth_views.PasswordChangeView.as_view(template_name='userauths/password-reset/change-password.html',success_url = '/user/password-reset-complete/'),name='change_password'),
    path('user/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='userauths/password-reset/password_reset_complete.html'), name='password_reset_complete'),

    

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


templates/chat/group_inbox_detail.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

    <!-- Main Contents -->
    <div class="main_content">

        <span uk-toggle="target: .message-content;" class="fixed left-0 top-36 bg-red-600 z-10 py-1 px-4 rounded-r-3xl text-white"> Users</span>

        <div class="messages-container">
            <div class="messages-container-inner">


                <div class="messages-inbox">
                    <div class="messages-headline">
                        <div class="input-with-icon" hidden>
                            <input id="autocomplete-input" type="text" placeholder="Search">
                            <i class="icon-material-outline-search"></i>
                        </div>
                        <h2 class="text-2xl font-semibold">Chats</h2>
                        <span class="absolute icon-feather-edit mr-4 text-xl uk-position-center-right cursor-pointer"></span>
                    </div>
                    <div class="messages-inbox-inner" data-simplebar>
                        <ul>
                            
                            {% for m in groupchat_list %}
                                <li>
                                    <a href="{% url 'core:group_inbox_detail' m.slug %}">
                                        <div class="message-avatar"><i class="status-icon status-online"></i><img src="{{m.images.url}}" alt=""></div>

                                        <div class="message-by">
                                            <div class="message-by-headline">
                                                <h5>{{m.name}}</h5>
                                            </div>
                                            <p>{{m.last_message.message|truncatechars:40}}</p>
                                        </div>
                                    </a>
                                </li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>


                <div class="message-content">

                    <div class="messages-headline">
                        <div class="flex">
                            {% if groupchat.images and groupchat.images.url %}
                                <img class="mr-1" src="{{ groupchat.images.url }}" style="width: 40px; height: 40px; object-fit: cover; border-radius: 50%;" alt="">
                            {% else %}
                                <div class="mr-1" style="width: 40px; height: 40px; border-radius: 50%; background-color: gray;"></div>
                            {% endif %}
                            <div>
                                <h4 class="ml-1">{{ groupchat.name }}</h4>
                                {% if groupchat.members.exists %}
                                    <p style="font-size: 13px; margin-top: -12px;">{{ groupchat.members.count }} Members</p>
                                {% else %}
                                    <p style="font-size: 13px; margin-top: -12px;">No Members Yet</p>
                                {% endif %}
                            </div>
                        </div>
                        
                        
                        <a href="{% url 'core:leave_group_chat' groupchat.slug  %}" class="message-action text-red-500"><i class="fas fa-sign-out-alt"></i> <span class="md:inline hidden">Leave Group</span> </a>
                    </div>

                    <div class="message-content-scrolbar" data-simplebar>

                        <!-- Message Content Inner -->
                        <div class="message-content-inner chat_container" style="overflow-y: scroll; max-height: 550px; height: auto; ">

                            <!-- Time Sign -->
                            <div class="message-time-sign">
                                <span>Created on {{groupchat.date|date:"d M, Y"}}</span>
                            </div>

                            
                            {% for m in group_messages %}
                            
                                {% if m.sender == request.user %}
                                    <div class="message-bubble me">
                                        <div class="message-bubble-inner">
                                            <div class="message-avatar"><img src="{{ m.sender.profile.image.url }}" alt=""></div>
                                            <div class="message-text">
                                                <p>{{m.message}}</p>
                                                <p style="color: rgba(255, 255, 255, 0.479);"><small>{{ m.date|timesince }} ago - {{ m.sender.profile.full_name }}</small></p>
                                            </div>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                {% else %}
                                    <div class="message-bubble">
                                        <div class="message-bubble-inner">
                                            <div class="message-avatar"><img src="{{ m.sender.profile.image.url }}" alt=""></div>
                                            <div class="message-text">
                                                <p>{{m.message}}</p>
                                                <p style="color: gray"><small>{{ m.date|timesince }} ago - {{ m.sender.profile.full_name }}</small></p>

                                            </div>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                {% endif %}
                            {% endfor %}
                            <div id="chat-messages"></div>

                        </div>

                        <!-- Reply Area -->
                        <div class="message-reply">
                            <textarea id="chat-input" cols="1" rows="1" placeholder="Write Message"></textarea>
                            <button id="send-btn" class="button ripple-effect" >Send</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        $(function() {
            var group_name = "{{group_name}}";
            var groupchat_id = "{{groupchat.id}}";

            console.log(group_name);
            console.log(groupchat_id);
    
            var socket = new WebSocket('ws://' + window.location.host + '/ws/group-chat/' + group_name + '/');
    
            socket.onopen = function() {
                console.log('WebSocket connection established.');
            }
    
            socket.onmessage = function(event) {
                console.log(event);
                var data = JSON.parse(event.data);
                var message = data.message;
                var sender = data.sender;
                var profileImage = data.profile_image;
                var groupchat_id = data.groupchat_id;
                var full_name = data.full_name
                var date = data.date
     
                if (sender === "{{request.user}}") {
                        var chatMessage = '<div class="message-bubble me">';
                        chatMessage += '<div class="message-bubble-inner">';
                        chatMessage += '<div class="message-avatar"><img src="' + profileImage + '" alt=""></div>';
                        chatMessage += '<div class="message-text">';
                        chatMessage += '<p>' + message + '</p>';
                        chatMessage += '<p style="color: rgba(255, 255, 255, 0.479);"><small>' + date + ' ago - ' + full_name + '</small></p>'

                        chatMessage += '</div>';
                        chatMessage += '</div>';
                        chatMessage += '<div class="clearfix"></div>';
                        chatMessage += '</div>';
                        // Append the chat message to the main div
                        $('#chat-messages').append(chatMessage);
                        // Get the chat container
                        var chatContainer = document.querySelector('.chat_container');
                        // Automatically scroll to the bottom of the message after sending.
                        chatContainer.scrollTop = chatContainer.scrollHeight;
                } else {
                    var chatMessage = '<div class="message-bubble">';
                        chatMessage += '<div class="message-bubble-inner">';
                        chatMessage += '<div class="message-avatar"><img src="' + profileImage + '" alt=""></div>';
                        chatMessage += '<div class="message-text">';
                        chatMessage += '<p>' + message + '</p>';
                        chatMessage += '<p style="color: gray"><small>' + date + ' ago - ' + full_name + '</small></p>'
                        chatMessage += '</div>';
                        chatMessage += '</div>';
                        chatMessage += '<div class="clearfix"></div>';
                        chatMessage += '</div>';
                        $('#chat-messages').append(chatMessage);

                        var chatContainer = document.querySelector('.chat_container');
                        chatContainer.scrollTop = chatContainer.scrollHeight;
                        console.log("No");
                }
            }
    
            socket.onclose = function() {
                console.log('WebSocket connection closed.');
            }
    
            $('#send-btn').on('click', function() {
                var input = $('#chat-input');
                var message = input.val();
                var sender = "{{request.user.username}}"; 
                var data = {
                    'message': message,
                    'sender': sender,
                    'groupchat_id': 1,
                };
                socket.send(JSON.stringify(data));
                input.val('');
                var sendButton = $('#send-btn');
                sendButton.prop('disabled', true);
                $(".chat_container").scrollTop(100000000000);
            });
    
        });


       


        $(document).ready(function() {
          $(".chat_container").scrollTop(100000000000);
        });

    </script>

    <script>
       $(document).ready(function() {
            var chatInputValue = $('#chat-input');
            var sendButton = $('#send-btn');

            // Disable the button initially
            sendButton.prop('disabled', true);

            // Check input field on keyup event
            chatInputValue.on('keyup', function() {
                var inputText = $(this).val();

                // Enable/disable button based on input field value
                if (inputText.trim() !== '') {
                    sendButton.prop('disabled', false);
                } else {
                    sendButton.prop('disabled', true);
                }
            });
        })
    </script>


    

    {% endblock content %}

templates/chat/inbox_detail.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

    <!-- Main Contents -->
    <div class="main_content">
        <span uk-toggle="target: .message-content;" class="fixed left-0 top-36 bg-red-600 z-10 py-1 px-4 rounded-r-3xl text-white"> Users</span>

        <div class="messages-container">
            <div class="messages-container-inner">


                <div class="messages-inbox">
                    <div class="messages-headline">
                        <div class="input-with-icon" hidden>
                            <input id="autocomplete-input" type="text" placeholder="Search">
                            <i class="icon-material-outline-search"></i>
                        </div>
                        <h2 class="text-2xl font-semibold">Chats</h2>
                        <span class="absolute icon-feather-edit mr-4 text-xl uk-position-center-right cursor-pointer"></span>
                    </div>
                    <div class="messages-inbox-inner" data-simplebar>
                        <ul>
                            
                            {% for m in chat_message %}
                                {% if request.user == m.sender %}
                                    <li>
                                        <a href="{% url 'core:inbox_detail' m.reciever.username %}">
                                            <div class="message-avatar"><i class="status-icon status-online"></i><img src="{{m.reciever.profile.image.url}}" alt=""></div>

                                            <div class="message-by">
                                                <div class="message-by-headline">
                                                    <h5>{{m.reciever.profile.full_name}}</h5>
                                                    <span>{{m.date|timesince}} ago</span>
                                                </div>
                                                <p>{{m.message|truncatechars:40}}</p>
                                            </div>
                                        </a>
                                    </li>
                                {% endif %}

                                {% if request.user == m.reciever %}
                                    <li>
                                        <a href="{% url 'core:inbox_detail' m.sender.username %}">
                                            <div class="message-avatar"><i class="status-icon status-online"></i><img src="{{m.sender.profile.image.url}}" alt=""></div>

                                            <div class="message-by">
                                                <div class="message-by-headline">
                                                    <h5>{{m.sender.profile.full_name}}</h5>
                                                    <span>{{m.date|timesince}} ago</span>
                                                </div>
                                                <p>{{m.message|truncatechars:40}}</p>
                                            </div>
                                        </a>
                                    </li>
                                {% endif %}
                            {% endfor %}

                        </ul>
                    </div>
                </div>


                <div class="message-content">

                    <div class="messages-headline">
                        <div class="flex">
                            <img class="mr-1" src="{{ receiver_details.profile.image.url }}" style="width: 40px; height: 40px; object-fit: cover; border-radius: 50%;" alt="">
                            <h4 class="ml-1"> {{ receiver_details.profile.full_name|title }} </h4>
                        </div>
                        
                        {% if receiver_details in request.user.profile.friends.all %}
                            <a href="#" id="block-user-btn" data-block-user="{{receiver_details.id}}" class="message-action text-red-500 "><i class="fas fa-ban"></i> <span class="md:inline hidden block-text{{receiver_details.id}}" > Block {{ receiver_details.profile.full_name|title }}</span> </a>
                        {% endif %}
                            
                    </div>

                    <div class="message-content-scrolbar ">

                        <!-- Message Content Inner -->
                        <div class="message-content-inner chat_container" style="overflow-y: scroll; max-height: 550px; height: auto; ">

                           
                            {% for m in message_detail %}
                                {% if m.sender == request.user %}
                                <div class="message-bubble me">
                                    <div class="message-bubble-inner">
                                        <div class="message-avatar"><img src="{{m.sender.profile.image.url}}" alt=""></div>
                                        <div class="message-text">
                                            <p>{{m.message}}</p>
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                                {% else %}
                                <div class="message-bubble">
                                    <div class="message-bubble-inner">
                                        <div class="message-avatar"><img src="{{m.sender.profile.image.url}}" alt=""></div>
                                        <div class="message-text">
                                            <p>{{m.message}}</p>
                                            <p class="text-muted"><small><span style="color: rgba(128, 128, 128, 0.596);">2:30</span></small></p>
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                                {% endif %}

                            {% endfor %}
                            <div id="chat-messages"></div>
                            
                        </div>
                        <!-- Message Content Inner / End -->

                        <!-- Reply Area -->
                        <div class="message-reply">
                            <textarea id="chat-input" cols="1" rows="1" placeholder="Write Message"></textarea>
                            <button id="send-btn" class="button ripple-effect" >Send</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
        
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        $(function() {
            var receiver = null;
            var receiver_id = "{{ reciever.username }}"; 
            var logged_in = "{{ request.user.username }}"; 
            const pathname = window.location.pathname;
    
            const parts = pathname.split('/');
            const username = parts[parts.length - 2];
    
            if (receiver_id === logged_in) {
                receiver = receiver_id;
            } else {
                receiver = receiver_id;
            }
    
            var socket = new WebSocket('ws://' + window.location.host + '/ws/chat/' + receiver + '/');
    
            socket.onopen = function() {
                console.log('WebSocket connection established.');
            }
    
            socket.onmessage = function(event) {
                var data = JSON.parse(event.data);
                var message = data.message;
                var sender = data.sender;
                var profileImage = data.profile_image;
                var reciever = data.reciever;
    
                if (sender === "{{sender}}") {
                        var chatMessage = '<div class="message-bubble me">';
                        chatMessage += '<div class="message-bubble-inner">';
                        chatMessage += '<div class="message-avatar"><img src="' + profileImage + '" alt=""></div>';
                        chatMessage += '<div class="message-text">';
                        chatMessage += '<p>' + message + '</p>';
                        chatMessage += '</div>';
                        chatMessage += '</div>';
                        chatMessage += '<div class="clearfix"></div>';
                        chatMessage += '</div>';
                        // Append the chat message to the main div
                        $('#chat-messages').append(chatMessage);
                        // Get the chat container
                        var chatContainer = document.querySelector('.chat_container');
                        // Automatically scroll to the bottom of the message after sending.
                        chatContainer.scrollTop = chatContainer.scrollHeight;
                } else {
                    var chatMessage = '<div class="message-bubble">';
                        chatMessage += '<div class="message-bubble-inner">';
                        chatMessage += '<div class="message-avatar"><img src="' + profileImage + '" alt=""></div>';
                        chatMessage += '<div class="message-text">';
                        chatMessage += '<p>' + message + '</p>';
                        chatMessage += '</div>';
                        chatMessage += '</div>';
                        chatMessage += '<div class="clearfix"></div>';
                        chatMessage += '</div>';
                        $('#chat-messages').append(chatMessage);

                        var chatContainer = document.querySelector('.chat_container');
                        chatContainer.scrollTop = chatContainer.scrollHeight;
                        console.log("No");
                }
            }
    
            socket.onclose = function() {
                console.log('WebSocket connection closed.');
            }
    
            $('#send-btn').on('click', function() {
                var input = $('#chat-input');
                var message = input.val();
                var sender = "{{request.user.username}}"; 
                var data = {
                    'message': message,
                    'sender': sender,
                    'reciever': username,
                };
                socket.send(JSON.stringify(data));
                input.val('');
                var sendButton = $('#send-btn');
                sendButton.prop('disabled', true);
                $(".chat_container").scrollTop(100000000000);
            });
    
        });


       


        $(document).ready(function() {
          $(".chat_container").scrollTop(100000000000);
        });

    </script>

    <script>
       $(document).ready(function() {
            var chatInputValue = $('#chat-input');
            var sendButton = $('#send-btn');

            // Disable the button initially
            sendButton.prop('disabled', true);

            // Check input field on keyup event
            chatInputValue.on('keyup', function() {
                var inputText = $(this).val();

                // Enable/disable button based on input field value
                if (inputText.trim() !== '') {
                    sendButton.prop('disabled', false);
                } else {
                    sendButton.prop('disabled', true);
                }
            });
        })
    </script>


{% endblock content %}

templates/chat/join_group_chat_page.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}
    <div class="main_content">
        <div class="mcontainer">

            <!--  breadcrumb -->
            <div class="breadcrumb-area py-0">
                <div class="breadcrumb">
                    <ul class="m-0">
                        <li>
                            <a href="index.html">Group Chat</a>
                        </li>
                        <li class="active">
                            <a href="#">{{groupchat.name}}<a>
                        </li>
                    </ul>
                </div>
            </div>


            <!-- create page-->
            <div class="max-w-2xl m-auto shadow-md rounded-md bg-white lg:mt-20">  

                <!-- form header -->
                <div class="text-center border-b border-gray-100 py-6">
                    <h3 class="font-bold text-xl">Join "{{groupchat.name}}" Chat</h3>
                </div>

                <!-- form body -->
                <div class="p-10 space-y-7">

                    <div class="line">
                        <input class="line__input" id="" name=""  type="text" value="{{groupchat.name}}" readonly autocomplete="off">
                        <span for="username" class="line__placeholder"> Group Chat Name </span>
                    </div>

                    <div class="line">
                        <input class="line__input" id="" name=""  type="text" value="{{groupchat.host.profile.full_name}}" readonly autocomplete="off">
                        <span for="username" class="line__placeholder"> Group Chat Host</span>
                    </div>
                    
                    {% if groupchat.description %}
                    <div class="line">
                        <input class="line__input" id="" name=""  type="text" value="{{groupchat.description}}" readonly autocomplete="off">
                        <span for="username" class="line__placeholder"> Group Chat Description</span>
                    </div>
                    {% endif %}

                    <div class="line">
                        <input class="line__input" id="" name=""  type="text" value="{{groupchat.members.all.count}} Members" readonly autocomplete="off">
                        <span for="username" class="line__placeholder"> Group Chat Members</span>
                    </div>
                    
                </div>
                
                <!-- form footer -->
                <div class="flex justify-center border-gray-100 py-8">
                    <a href="{% url 'core:join_group' groupchat.slug  %}" class="button lg:w-1/3"> Join Group Chat </a>
                </div>
                
            </div>

    
        </div>
    </div>
{% endblock content %}